export const details = [
    {
      id: 1,
      name: 'Vasu ',
      lastmsg: 'hello...',
      profilePic: 'https://reqres.in/img/faces/1-image.jpg',
      date: '',
      lastSeen: '11:28 AM',
    },
    {
      id: 2,
      name: 'kamal Appinventiv',
      lastmsg: 'Okk..',
      profilePic: 'https://reqres.in/img/faces/2-image.jpg',
      date: '',
      lastSeen: '10:48 AM',
    },
    {
      id: 3,
      name: 'PushpaRaj Appinventiv',
      lastmsg: 'hello.....',
      profilePic: 'https://reqres.in/img/faces/3-image.jpg',
      date: '',
      lastSeen: '3:33 PM',
    },
    {
      id: 4,
      name: 'Shivam Appinventiv',
      lastmsg: 'Hi there i m using WhatsApp',
      profilePic: 'https://reqres.in/img/faces/4-image.jpg',
      date: '',
      lastSeen: 'Yesterday.',
    },
    {
      id: 5,
      name: 'Reeturaj Appinevtiv',
      lastmsg: 'hello...',
      profilePic: 'https://reqres.in/img/faces/5-image.jpg',
      date: '',
      lastSeen: '12/4/22',
    },
    {
      id: 6,
      name: 'Tanmay College',
      lastmsg: 'Hi there i m using WhatsApp...',
      profilePic: 'https://reqres.in/img/faces/6-image.jpg',
      date: '',
      lastSeen: '17/3/22',
    },
    {
      id: 7,
      name: 'Ashutosh Dubey',
      lastmsg: 'okay fine...',
      profilePic: 'https://reqres.in/img/faces/7-image.jpg',
      date: '',
      lastSeen: '1/1/22',
    },
    {
      id: 8,
      name: 'Sumit Psit',
      lastmsg: 'hello...',
      profilePic: 'https://reqres.in/img/faces/8-image.jpg',
      date: '',
      lastSeen: '11:28 AM',
    },
    {
      id: 9,
      name: 'Ayan Alam Psit',
      lastmsg: 'hello...',
      profilePic: 'https://reqres.in/img/faces/9-image.jpg',
      date: '',
      lastSeen: '11:28 AM',
    },
    {
      id: 10,
      name: 'Jitendra Psit',
      lastmsg: 'hello...',
      profilePic: 'https://reqres.in/img/faces/10-image.jpg',
      date: '',
      lastSeen: '11:28 AM',
    },
    {
      id: 11,
      name: 'Akshat Appinventiv',
      lastmsg: 'hello...',
      profilePic: 'https://reqres.in/img/faces/11-image.jpg',
      date: '',
      lastSeen: '11:28 AM',
    },
    {
      id: 12,
      name: 'Abhisek Ojha Appinventiv',
      lastmsg: 'Good friday .. ',
      profilePic: 'https://reqres.in/img/faces/12-image.jpg',
      date: '',
      lastSeen: '11:28 AM',
    },
    {
      id: 13,
      name: ' Vaibhav Psit',
      lastmsg: 'hello...',
      profilePic: 'https://reqres.in/img/faces/9-image.jpg',
      date: '',
      lastSeen: '11:28 AM',
    },
    {
      id: 14,
      name: 'Masroor Ali',
      lastmsg: 'hello...',
      profilePic: 'https://reqres.in/img/faces/12-image.jpg',
      date: '',
      lastSeen: '11:28 AM',
    },
    {
      id: 15,
      name: 'Ashad Ali',
      lastmsg: 'hello...',
      profilePic: 'https://reqres.in/img/faces/2-image.jpg',
      date: '',
      lastSeen: '11:28 AM',
    },
  ];
  